### ISSUE TITLE
Sort by date - newest first by default

### ISSUE THREAD

**Issue by rostyaka** [CyborgTests/playwright-reports-server#15]
**Steps to reproduce**
Upload a couple of reports

**Actual result**
Reports are sorted by ID which is not useful
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/b5b79438-c1ac-439d-a487-3a0a77740aaa">

**Expected result**
It would be good to show the newest reports first

**Comment by Xotabu4** [comment]
Closing as resolved
