### ISSUE TITLE
Whitelabel feature: Make server title and logo configurable

### ISSUE THREAD

**Issue by Xotabu4** [CyborgTests/playwright-reports-server#23]
- Users should be able to configure header name (like `My nice reports, SomeCompany reports, etc.`)
- Investigate posibility to set custom logo.

**Comment by Xotabu4** [comment]
@mstankovic feature added

**Comment by Shelex** [comment]
@mstankovic
Section about white-labelling is available in [readme](https://github.com/CyborgTests/playwright-reports-server?tab=readme-ov-file#ui-white-label)

It could be done just with single api call and to not let new build erase your changes `/data/` folder should be persisted, as will contain config file.
